version: "3"

services:
  common: &common
    image: swift:5.5
    volumes:
      - ..:/code
    working_dir: /code

  integration-tests:
    <<: *common
    environment:
      - MAX_ALLOCS_ALLOWED_1000_basicRoute=62000
      - MAX_ALLOCS_ALLOWED_1000_bodyInRequestRoute=65000
      - MAX_ALLOCS_ALLOWED_1000_bodyInResponseRoute=61000
    command: /bin/bash -xcl "./IntegrationTests/run-tests.sh $${INTEGRATION_TESTS_ARG-}"
